
import React from "react";
import Card from "./Card";
import Animate from "./Animate";
import { AlertTriangle } from "lucide-react";

const Disclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="py-20 bg-tattoo-dark">
      <div className="container mx-auto px-4">
        <Animate type="fade-in">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <span className="bg-tattoo-darker text-tattoo-neon px-4 py-1 rounded-full text-sm font-medium uppercase tracking-wider border border-tattoo-neon/30">
              Important
            </span>
            <h2 className="text-gradient mt-4 mb-6">Legal Disclaimer</h2>
          </div>
        </Animate>

        <Animate type="fade-in" delay={200}>
          <Card className="max-w-4xl mx-auto">
            <div className="flex items-start">
              <AlertTriangle className="h-8 w-8 text-tattoo-neon mr-4 flex-shrink-0 mt-1" />
              <div className="space-y-4 text-gray-300">
                <p>
                  <strong>Not Professional Medical or Legal Advice:</strong> TattooGPT is an AI assistant tool and does not provide professional medical, legal, or financial advice. The information provided is for general informational purposes only.
                </p>
                
                <p>
                  <strong>Consult Professionals:</strong> Always consult with qualified tattoo artists, licensed piercers, healthcare providers, and legal professionals before making decisions regarding tattoos, piercings, aftercare, or business practices.
                </p>
                
                <p>
                  <strong>No Warranty:</strong> TattooGPT and AI Web Tools LLC make no warranties, express or implied, regarding the accuracy, completeness, reliability, or suitability of the information provided. Use of the tool is at your own risk.
                </p>
                
                <p>
                  <strong>Health Considerations:</strong> Tattooing and piercing involve health risks including but not limited to infection, allergic reactions, and scarring. Users should research thoroughly and understand all associated risks before proceeding with any body modification.
                </p>
                
                <p>
                  <strong>Intellectual Property:</strong> Designs generated by TattooGPT are provided as conceptual inspiration only. Users are responsible for ensuring any designs used comply with copyright and intellectual property laws. TattooGPT does not claim ownership of designs created by users with its assistance.
                </p>
                
                <p>
                  <strong>Business Compliance:</strong> Information regarding tattoo shop business planning is general guidance only. Users are responsible for ensuring compliance with all applicable local, state, and federal regulations, including health codes, business licensing, and tax requirements.
                </p>
                
                <p>
                  <strong>Age Restrictions:</strong> Users must comply with minimum age requirements for tattoos and piercings in their jurisdiction. TattooGPT is not intended to facilitate services for individuals under legal age.
                </p>
                
                <p>
                  <strong>Limitation of Liability:</strong> AI Web Tools LLC, its affiliates, and partners shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in connection with the use of TattooGPT or any information it provides.
                </p>
                
                <p>
                  By using TattooGPT, you acknowledge that you have read, understood, and agree to these disclaimers and limitations.
                </p>
              </div>
            </div>
          </Card>
        </Animate>
      </div>
    </section>
  );
};

export default Disclaimer;
